use_frameworks!

platform :ios, '12.0'

pod 'LayoutTestBase/Swift', :path => '..'

target :SampleApp do
end

target :CatalogSample do
end

target :SampleAppTests do
  pod 'LayoutTest/Swift', :path => '..'
end
